# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.version.version)
print(np.show_config())

1.22.1
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [6]:
x=np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [7]:
print(x.size)
print(x.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [9]:
y=np.zeros(10)
y[4]=1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [10]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [11]:
print(z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [12]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [14]:
a=np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [15]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [18]:
print(np.random.random((3,3,3)))

[[[0.26353856 0.46951128 0.76356954]
  [0.78471431 0.17477225 0.34449399]
  [0.85935386 0.06643342 0.6569678 ]]

 [[0.16522356 0.73088135 0.88951579]
  [0.1024565  0.90883148 0.12017004]
  [0.81209509 0.64517497 0.8443249 ]]

 [[0.09562484 0.33702221 0.22023954]
  [0.7821921  0.58701923 0.76002671]
  [0.3282185  0.95158165 0.56715189]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [19]:
arr=np.random.random((10,10))
min=arr.min()
max=arr.max()
print(arr)
print(min)
print(max)

[[5.98962631e-01 5.38168854e-01 4.97536498e-02 8.46503287e-01
  8.68859241e-01 1.59798022e-01 3.02996443e-01 4.97302714e-01
  3.61732910e-01 6.70132771e-01]
 [9.78158592e-01 8.35296832e-01 7.53777254e-01 3.19145859e-01
  6.77643349e-01 2.67092348e-01 7.92676297e-02 8.33802270e-01
  9.45961874e-01 5.98173011e-01]
 [4.76918396e-01 8.35911503e-01 7.32044830e-01 1.87285020e-01
  5.49344210e-01 6.30035049e-01 5.97744923e-01 8.53489439e-01
  1.99611589e-01 2.30720443e-01]
 [8.01184602e-01 9.54609950e-01 2.18740900e-01 8.54196170e-01
  5.75225841e-01 3.41915075e-01 7.41649171e-02 5.90811220e-01
  6.16029288e-01 4.02400108e-01]
 [4.26202547e-01 9.46837442e-04 7.83394931e-01 1.59717716e-01
  2.89952200e-01 9.36412454e-01 6.89194325e-01 6.78146369e-01
  2.36704160e-01 3.78634219e-01]
 [7.58267182e-01 6.12175116e-01 2.76642209e-01 5.56797401e-01
  9.80758014e-01 3.54657015e-02 6.61937631e-01 3.83421923e-01
  1.76576676e-01 9.34262069e-01]
 [8.38052493e-01 1.26897901e-01 5.73081304e-01 3.67531470e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [21]:
rv=np.random.random(30)
print(rv)
print(rv.mean())

[0.37065005 0.02957621 0.1372373  0.83778784 0.73537899 0.9192565
 0.72029969 0.10636282 0.71262241 0.47229603 0.44066183 0.14809185
 0.27951402 0.46800214 0.41582059 0.61857514 0.16124084 0.90484264
 0.65228673 0.57927529 0.88447704 0.60580133 0.47549199 0.24622009
 0.4338546  0.17265366 0.38762605 0.62165951 0.00401346 0.03287349]
0.45248167110659465


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [26]:
r=np.ones((5,5))
r[1:-1,1:-1]=0
print(r)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [31]:
nr=np.ones((3,3))
nr=np.pad(nr,pad_width=1,mode='constant',constant_values=0)
print(nr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [34]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [38]:
print(np.diag((0,1,2,3,4)))

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [43]:
m=np.zeros((8,8))
m[1::2, ::2] = 1
m[::2, 1::2] = 1
print(m)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [16]:
sa = np.unravel_index(100, (6,7,8))
sa

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [17]:
import numpy as np
def printcheckboard(n):
    final = []
    for i in range(n):
        final.append(list(np.tile([0,1],int(n/2))) if i%2==0 else list(np.tile([1,0],int(n/2))))
    print(np.array(final))
  
  
# driver code
n = 8
printcheckboard(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [18]:
x= np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.87015157 0.         0.17019155 0.15653843 1.        ]
 [0.41326875 0.50115179 0.26839617 0.87756968 0.67732506]
 [0.53116984 0.45228551 0.10921444 0.90347294 0.06276042]
 [0.37545705 0.98686762 0.88963612 0.63369004 0.15060467]
 [0.02655391 0.30759727 0.38748254 0.25761164 0.83782169]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [32]:
dt = np.dtype([('color', np.unicode_, 16), ('rgba', np.uint64, (4,))])
 
x = np.array([('Red', (244,67,54,1))], dtype=dt)
 
print(x)
print("RGBA color code of red is: ",x['rgba'])


[('Red', [244,  67,  54,   1])]
RGBA color code of red is:  [[244  67  54   1]]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [33]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x, y)

print(z)

[[0.67809041 0.52695829]
 [0.50030133 0.41647507]
 [0.70312812 0.61402494]
 [0.71493324 0.43290133]
 [0.91853091 0.74429427]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [43]:
oda=np.arange(11)
oda[3:8] *=-1
oda

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [44]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [65]:
Z=10

ar=[Z**Z,2 << Z >> 2,Z <- Z,1j*Z,Z/1/1,Z<Z>Z]
arn=[]

for i in ar:
    if i!=False:
        arn.append(i)

print("The legal expressions are: ",arn) 

The legal expressions are:  [10000000000, 512, 10j, 10.0]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [5]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [69]:
def round_array(x,y):
    return np.round(x,y)

t = np.array([32.11, 51.5, 0.112])

print(round_array(t,0))


[32. 52.  0.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [70]:
x = np.array([0, 1, 2, 3, 4]) 
y = np.array([0, 2, 4])
print(np.intersect1d(x, y)) 

[0 2 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [3]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [7]:
if np.sqrt(-1) == np.emath.sqrt(-1):
        print("True")
else:
        print("False")

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [11]:
today = np.datetime64('today', 'D')
print("Today: ", today)
  
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ", yesterday)
  
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Today:  2022-02-21
Yesterday:  2022-02-20
Tomorrow:  2022-02-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [15]:
print("July, 2016")
print(np.arange('2016-07','2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [18]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print(A)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [20]:
x = np.random.uniform(-10, +10, 10)
print(x.astype(np.int32))
print(np.trunc(x))
print(np.floor(x))

[-8 -1  2  3 -5 -3 -9  2 -9  3]
[-8. -1.  2.  3. -5. -3. -9.  2. -9.  3.]
[ -9.  -2.   2.   3.  -6.  -4. -10.   2. -10.   3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [23]:
x = np.zeros((5, 5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [24]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [26]:
np.linspace(start=0, stop=1, num=10, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [31]:
x = np.random.random(size=10)
x.sort()
print(x)

[0.11045101 0.23236975 0.43210703 0.45843712 0.49735446 0.50321219
 0.57764447 0.76010053 0.80097114 0.84518936]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [3]:
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

3.9985179901123047
3.514528274536133


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [7]:
a = np.random.random(10)
print(a)
b = np.random.random(10)
print(b)
np.array_equal(a, b)

[0.13988623 0.89115878 0.11742892 0.21218249 0.89837241 0.83598168
 0.72530223 0.75504583 0.2233008  0.49538829]
[0.19968637 0.3938066  0.55645601 0.19823613 0.61860523 0.04092979
 0.87406322 0.73531495 0.06435606 0.9381349 ]


False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [8]:
x = np.zeros(10)
x.flags.writeable = False
x[1] = 1 

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [11]:
z = np.random.random((10, 2))
print(Z)
x, y = Z[:, 0], Z[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
t = np.arctan2(y, x)
print(r)
print(t)

[[0.66203371 0.98921852]
 [0.25683958 0.29074681]
 [0.50643133 0.3819007 ]
 [0.24921459 0.66799356]
 [0.62641933 0.51599446]
 [0.72302251 0.06742046]
 [0.81502763 0.61109512]
 [0.19786009 0.88200433]
 [0.6263761  0.33391568]
 [0.53683289 0.21263282]]
[1.19031169 0.38794365 0.63428767 0.71296795 0.81157345 0.72615912
 1.01867919 0.90392491 0.7098216  0.57740996]
[0.98100794 0.84724045 0.646121   1.2137106  0.68903825 0.09297921
 0.6433632  1.35011963 0.48976892 0.37712903]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [12]:
x = np.random.random(10)
print(x)
x[x == np.max(x)] = 0
x[x.argmax()] = 0
print(x)

[0.64280091 0.17835569 0.08891443 0.96697776 0.9076811  0.55734396
 0.21190647 0.23798799 0.94771761 0.46838252]
[0.64280091 0.17835569 0.08891443 0.         0.9076811  0.55734396
 0.21190647 0.23798799 0.         0.46838252]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [14]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [15]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[ 9.82096785e+04, -4.78594982e+06, -8.79343532e+04,
        -1.82119854e+06, -8.86535872e+04],
       [ 1.63178435e+05, -4.91035138e+07, -9.57126487e+06,
        -2.85240228e+05, -9.47564584e+01],
       [-2.43829207e+06,  9.42003548e+04,  1.46297211e+05,
        -5.95500910e+05,  3.63931529e+05],
       [-3.33963444e+05,  3.10707104e+07, -1.52203253e+07,
        -2.71326942e+05,  1.55918370e+06],
       [ 5.92000680e+06, -1.62385523e+02, -1.42661345e+02,
         1.79398245e+05, -2.74790709e+08]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [16]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [17]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [21]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z[index])

24


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [4]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\balaj\AppData\Local\Temp\ipykernel_21952\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [7]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.62393769 0.63777182 0.59753302 0.34325767 1.0362633
  0.70377595 0.6130291  0.57896815 0.40738787]
 [0.62393769 0.         0.86369622 0.80515796 0.76111489 0.517619
  0.1677812  0.41031807 0.06159501 0.30266287]
 [0.63777182 0.86369622 0.         0.05855928 0.97976835 0.94876934
  0.80541463 0.50585406 0.86439849 0.86923314]
 [0.59753302 0.80515796 0.05855928 0.         0.94063822 0.90096366
  0.74830501 0.45087093 0.80590402 0.81395789]
 [0.34325767 0.76111489 0.97976835 0.94063822 0.         1.25304944
  0.89325883 0.89916906 0.7017229  0.46229765]
 [1.0362633  0.517619   0.94876934 0.90096366 1.25304944 0.
  0.36222242 0.47973986 0.57858064 0.81253787]
 [0.70377595 0.1677812  0.80541463 0.74830501 0.89325883 0.36222242
  0.         0.30856673 0.22439956 0.45087227]
 [0.6130291  0.41031807 0.50585406 0.45087093 0.89916906 0.47973986
  0.30856673 0.         0.43556788 0.56086061]
 [0.57896815 0.06159501 0.86439849 0.80590402 0.7017229  0.57858064
  0.22439956 0.43556788

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [8]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[78 97 51 49 58 89 55 45 97 62]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [10]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\balaj\AppData\Local\Temp\ipykernel_21952\2687400857.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [11]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [12]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [13]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [14]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[-0.2943729   0.2411407   0.1875811   0.02982    -0.31447886  0.058538
   0.33503737 -0.21296962  0.35815503 -0.38845083]
 [-0.04030817 -0.27018448  0.3927079  -0.30177785 -0.50004312  0.38529194
   0.30891988 -0.23976334  0.11555965  0.14959759]
 [-0.3415413   0.28077047 -0.28278147  0.26731908  0.12718183  0.0536098
   0.10731198 -0.21733851 -0.02994805  0.03541618]
 [-0.11750534 -0.32129492  0.11231629 -0.24858627 -0.00396565  0.13578291
   0.1887249   0.35754417 -0.39007145  0.28705537]
 [-0.28124156  0.13405269  0.46704348  0.03992016 -0.17621434 -0.25537622
   0.01212531  0.2360076   0.20133628 -0.37765338]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [15]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 1 8]
 [3 0 8]
 [5 6 0]]
[[3 0 8]
 [8 1 8]
 [5 6 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [16]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [4]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5010245881716207


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [5]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [6]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [7]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[3. 4. 5. 3. 5. 5. 1. 1. 2. 1.]
[5. 7. 9. 5. 9. 9. 1. 1. 3. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [8]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [9]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

I24 = np.dot(I.astype(np.uint32),[1,256,65536])
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [10]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[60 38 55 62]
 [51 47 64 39]
 [69 32 46 73]]
[[60 38 55 62]
 [51 47 64 39]
 [69 32 46 73]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [11]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.57720727 0.59902887 0.59150994 0.5035263  0.55993448 0.49134205
 0.58513078 0.37003218 0.44428676 0.68964518]
0    0.577207
1    0.599029
2    0.591510
3    0.503526
4    0.559934
5    0.491342
6    0.585131
7    0.370032
8    0.444287
9    0.689645
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [13]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([0.90443264, 0.91236846, 0.65920662, 0.08770215, 0.94329755])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [14]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [15]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [16]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [17]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3,  9) ( 3, 83) ( 9, 83) (12, 21) (12, 79) (16, 86) (16, 91) (19, 89)
 (19, 96) (21, 79) (22, 81) (22, 86) (24, 26) (24, 39) (26, 39) (34, 54)
 (34, 97) (54, 97) (57, 68) (57, 74) (66, 67) (66, 72) (67, 72) (68, 74)
 (73, 93) (73, 95) (81, 86) (86, 91) (89, 96) (93, 95)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [18]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [19]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [20]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)
Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [21]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.91043435, -0.29092889,  0.21363515,  0.09458795, -0.7188038 ,
       -0.19391903, -0.87135977,  0.43266804, -0.83807881, -0.92280969,
        0.19608825, -0.0656026 , -0.92886731,  0.48966762,  0.7932826 ,
        0.29183713, -0.63911019, -0.07708661,  0.69435265, -0.11463489,
       -0.97197846,  0.35434218, -0.13192074, -0.9789235 ,  0.76673942,
       -0.42452211, -0.08885812, -0.0291771 , -0.96903298,  0.97351057,
       -0.19224616,  0.67332679,  0.89466218, -0.62452024,  0.7321224 ,
       -0.59683724,  0.26914721, -0.48039599,  0.76520288,  0.53310694,
        0.4767395 ,  0.53496025,  0.77045787,  0.25585299,  0.12346807,
       -0.34202527, -0.74964241, -0.47441884,  0.07221652,  0.35937443,
       -0.37347862, -0.32356689,  0.07059349,  0.57389674,  0.97371132,
       -0.97057806, -0.20706423,  0.83663467, -0.99262992, -0.48604789,
       -0.50318596, -0.30485293, -0.33945262,  0.80047517,  0.9347909 ,
       -0.71314237,  0.28898438, -0.89939179,  0.87561971, -0.13

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [22]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[0.55833022 0.90881041 4.55128188 8.07311337 0.32834256 4.77900692
 3.94034923 8.58192084 5.51335331 0.85315257]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [23]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.92644575  1.05474469  1.50586529  1.1076563   1.31961586  1.71304774
   7.42242973 10.20667845  6.82391849  2.58366846]
 [ 5.58739719  0.86177955  1.86229098  5.96078203  5.18596149  2.17850716
   3.63735385 10.84122168  5.15427672  7.48417235]
 [ 7.19537126 12.28914423  3.77524762  7.42932243 12.34200707 15.31845345
   3.95415189  4.16606539  3.6940689   4.24097008]
 [ 5.81960003 10.38865525 13.89517089 10.2231422   3.0259622   0.12208505
   7.88754408  0.66318326  7.20817818 13.24231264]
 [ 0.08682886  4.81781312  6.07586074  5.29903048  1.79797385  1.17098386
   0.06924133  5.22676301  0.22875108  7.56475409]
 [12.02635994 16.6210824  18.08278859  8.83769212  1.23017879  4.09504414
  11.46013433  5.60936735 12.91413328 12.66845621]
 [ 1.39716026  3.63308915  1.42621151  4.57592382  5.67198725  8.69806103
   8.21867719  4.70299918  3.94744079  2.51054999]
 [ 5.96034562  0.9864712   3.70660269  2.30398506  1.50058262  4.5494691
   9.93233955  9.56304513  7.79711918  0.83451752]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [24]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 1 7 0 7 0 7 7 9 5]
 [1 7 2 5 7 7 8 1 1 5]
 [6 3 6 4 4 9 2 2 6 1]
 [3 1 8 7 3 5 5 2 8 2]
 [2 3 1 7 7 4 6 5 8 6]
 [0 8 0 3 5 1 9 3 2 4]
 [8 8 3 3 8 1 2 4 9 3]
 [1 3 4 6 6 6 8 7 6 6]
 [7 5 6 2 1 6 1 8 8 0]
 [9 9 7 1 5 4 9 4 2 8]]
[[0 0 0 0 0]
 [0 5 1 7 0]
 [0 1 7 2 5]
 [0 6 3 6 4]
 [0 3 1 8 7]]


C:\Users\balaj\AppData\Local\Temp\ipykernel_13096\2794059638.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [25]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [26]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [27]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [28]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[1 2 1]
   [3 4 4]
   [3 0 3]]

  [[2 1 0]
   [4 4 1]
   [0 3 1]]

  [[1 0 4]
   [4 1 1]
   [3 1 2]]

  [[0 4 2]
   [1 1 4]
   [1 2 0]]

  [[4 2 0]
   [1 4 1]
   [2 0 0]]

  [[2 0 4]
   [4 1 0]
   [0 0 4]]

  [[0 4 3]
   [1 0 3]
   [0 4 1]]

  [[4 3 1]
   [0 3 2]
   [4 1 4]]]


 [[[3 4 4]
   [3 0 3]
   [2 2 0]]

  [[4 4 1]
   [0 3 1]
   [2 0 2]]

  [[4 1 1]
   [3 1 2]
   [0 2 3]]

  [[1 1 4]
   [1 2 0]
   [2 3 4]]

  [[1 4 1]
   [2 0 0]
   [3 4 1]]

  [[4 1 0]
   [0 0 4]
   [4 1 0]]

  [[1 0 3]
   [0 4 1]
   [1 0 0]]

  [[0 3 2]
   [4 1 4]
   [0 0 1]]]


 [[[3 0 3]
   [2 2 0]
   [4 0 3]]

  [[0 3 1]
   [2 0 2]
   [0 3 2]]

  [[3 1 2]
   [0 2 3]
   [3 2 3]]

  [[1 2 0]
   [2 3 4]
   [2 3 0]]

  [[2 0 0]
   [3 4 1]
   [3 0 0]]

  [[0 0 4]
   [4 1 0]
   [0 0 0]]

  [[0 4 1]
   [1 0 0]
   [0 0 2]]

  [[4 1 4]
   [0 0 1]
   [0 2 2]]]


 [[[2 2 0]
   [4 0 3]
   [0 3 2]]

  [[2 0 2]
   [0 3 2]
   [3 2 0]]

  [[0 2 3]
   [3 2 3]
   [2 0 2]]

  [[2 3 4]
   [2 3 0]
   [0 2 1]]

  [[3 4 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [29]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8  8  9  1 14]
 [ 8  9 10  5  1]
 [ 9 10  6 42  9]
 [ 1  5 42  7  9]
 [14  1  9  9  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [30]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [31]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

Z = np.ones((16,16))
k = 4
windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [32]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [33]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
# Slow
print (Z[np.argsort(Z)[-n:]])
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9996 9999 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [34]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [35]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [58]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.38 s ± 76.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
340 ms ± 19.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
203 ms ± 12.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [60]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [59]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 0 2]
 [0 4 2]
 [4 2 2]
 [2 0 0]
 [3 4 1]
 [0 4 1]
 [1 3 3]
 [1 4 1]
 [3 0 3]
 [0 0 2]]
[[2 0 2]
 [0 4 2]
 [4 2 2]
 [2 0 0]
 [3 4 1]
 [0 4 1]
 [1 3 3]
 [1 4 1]
 [3 0 3]
 [0 0 2]]
[[2 0 2]
 [0 4 2]
 [4 2 2]
 [2 0 0]
 [3 4 1]
 [0 4 1]
 [1 3 3]
 [1 4 1]
 [3 0 3]
 [0 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [61]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [62]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [63]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B)   

array([[0.54355199, 0.7697501 , 0.44150389, 0.73322708, 0.81539202,
        0.34491447, 0.70897126, 0.4446228 , 0.84657203, 0.86710383],
       [0.02660948, 0.03768296, 0.02161374, 0.03589499, 0.03991735,
        0.01688522, 0.03470755, 0.02176642, 0.04144377, 0.0424489 ],
       [0.25306638, 0.35837947, 0.20555493, 0.34137512, 0.37962938,
        0.16058492, 0.33008212, 0.20700703, 0.39414614, 0.40370532],
       [0.12673215, 0.1794715 , 0.10293907, 0.17095595, 0.19011316,
        0.08041872, 0.16530057, 0.10366627, 0.19738295, 0.20217006],
       [0.16027127, 0.22696785, 0.13018145, 0.2161987 , 0.24042578,
        0.10170118, 0.20904665, 0.13110109, 0.2496195 , 0.25567348],
       [0.20860763, 0.29541929, 0.169443  , 0.28140227, 0.31293602,
        0.13237333, 0.27209322, 0.17063999, 0.32490247, 0.33278228],
       [0.07850143, 0.11116965, 0.06376333, 0.10589489, 0.1177614 ,
        0.0498136 , 0.10239179, 0.06421378, 0.12226451, 0.12522977],
       [0.07334133, 0.10386218, 0.0595720

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [69]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [66]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [68]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.16935445  0.21207981]
